# Default values for md-custom-r.
#
image:
environment:
  name:
  jobName: MD custom R
  awsRegion:
  serviceAccountName:
  sourceBucket:
  resultsBucket:
  flow: prepare_input_transform_intensities
  flowPackage: md_custom_r.process_r
  deploymentName: process-r-deployment
  datasetRunType: INTENSITY
prefect:
  apiUrl: http://prefect-server:4200/api
