steps:
  ################################################################################
  ## Image
  ################################################################################
  - block: ":warning: build and push docker images?"
    key: block_image
    depends_on: prep
    branches: "!main"

  - label: ":docker: dataset package: build & push image"
    key: build_python_image
    depends_on: ["block_image"]
    command: scripts/build-push
    env:
      AWS_REGION: "ap-southeast-2"
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_PROFILE: "eb-services-cli"
      BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
      DOCKER_FILE: "Dockerfile"
      REPO_NAME: "md_custom_r"
      DATASET_PACKAGE_VERSION: "v0.3.8-105"
    agents:
      ebdeploy: true
    concurrency: 1
    concurrency_group: "md_custom_r/docker"

  - wait: ~
    key: prep

  - label: ':helm: development: deploy'
    key: deploy_dev
    depends_on: prep
    commands: scripts/deploy
    env:
      ENVIRONMENT: 'development'
      AWS_PROFILE: 'tf-development-cli'
    retry:
      manual:
        permit_on_passed: true
    agents:
      terraform: true
    concurrency: 1
    concurrency_group: 'development/converter/deploy'
